version: '1.0.2'

services:
  api:
    image: parrotweb/animal-shelter-api:latest
    build: ./AnimalShelter/
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5003:80"
    volumes:
      - animal-shelter-data:/app/Database/
      - animal-shelter-wwwroot:/app/wwwroot/

volumes:
  animal-shelter-data:
  animal-shelter-wwwroot:
    